//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBonos
    {
        public int IdBonos { get; set; }
        public string Departamento { get; set; }
        public decimal Bono { get; set; }
        public string Motivo { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdUsuarios { get; set; }
    
        public virtual tblUsuarios tblUsuarios { get; set; }
    }
}
